### ISSUE TITLE
编译字节码奔溃

### ISSUE THREAD

**Issue by yubaokang** [HarlonWang/quickjs-android-wrapper#12]
![fd545357ff08f31c5abc866223bc6fd6](https://user-images.githubusercontent.com/7115700/172598294-f156847b-b0a7-4351-89b1-c7fe63eba300.jpg)
![4b10990b20c70da679896dc6db6453f0](https://user-images.githubusercontent.com/7115700/172598244-926c2c30-5bbe-40ee-8dd7-611d0cce2491.jpg)

**Comment by yubaokang** [comment]
at apply (native)
at <anonymous> (compile.js)
at forEach (native)
at value (compile.js)
at createApp (compile.js)
at App (compile.js)
at <anonymous> (compile.js)
at value (compile.js)
at <eval> (compile.js:1)

QuickJSContext.execute(Native Method)
QuickJSContext.execute(QuickJSContext.java:236)
QuickJSHelper.executeByteArra
QuickJSHelper.executeByteArra
executeByteArray(Base.JS
executeJSPath(BaseJSEn

**Comment by HarlonWang** [comment]
看起来是 js 异常导致，可以给个最小测试代码，我这边复现看下？
