### ISSUE TITLE
Promise错误能否支持一下？

### ISSUE THREAD

**Issue by yubaokang** [HarlonWang/quickjs-android-wrapper#13]
Promise错误能否支持一下？

@Test
    fun testPromise(){
        context.evaluate("""
            new Promise(
                ()=>console.log(aaaa)
            )
        """.trimIndent())
    }

**Comment by yubaokang** [comment]
自己尝试去加，但是无奈现阶段对c++和jni不是很熟悉，没能加上

**Comment by HarlonWang** [comment]
这个在需求计划中了哈~预计7月中旬左右

**Comment by HarlonWang** [comment]
另外，临时方案可通过添加 catch 来捕获异常：

```javascript
new Promise(() => {
	console.log(aaaa);
}).catch((err) => {
	console.log(err);// ReferenceError: 'aaaa' is not defined
});
```

**Comment by yubaokang** [comment]
业务方可能就没写catch

**Comment by HarlonWang** [comment]
是的，这个特性我会优先支持下 :)

**Comment by HarlonWang** [comment]
@yubaokang 已支持，https://github.com/HarlonWang/quickjs-android-wrapper/commit/c4f1ba97ba6e442da949ecf3d9202b9664e81d79
